#是否启用？
enable: true

#通常是压力板
top-block: 'STONE_PLATE'

#起飞后的消息
chat-enable: true
message: '&e芜湖~起飞！'

#英文用户起飞后的消息
en-chat-enable: true
en-message: '&eHoooosh!'

#禁用掉落伤害？
yea: true
#落地后是否发消息？仅限中文用户
fall: true
#落地后发的消息？仅限中文用户
fall-msg: 'U FALL'
#飞多高？
Y: 1
#飞多远？
M: 2

x: 0
z: -0.5